
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_LITE_counter(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

counter #(
.WIDTH (10))
c0 ( .clk (KEY[0]),
.clrn (KEY[1]),
.q (LEDR));

//assign LEDR = KEY; // FAZ ALGUMA COISA

endmodule
