
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_LITE_FSM(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

FSM FSM0 ( .CLK (KEY[0]),
 .CLR (KEY[1]),
 .OP (SW[1:0]),
 .FUNCT3 (SW[4:2]),
 .ZERO (SW[5]),
 .PCWrite (HEX5[7]),
 .AdrSrc (HEX4[7]),
 .MemWrite (HEX3[7]),
 .IRWrite (HEX2[7]),
 .ResultSrc ({HEX1[7],HEX0[7]}),
 .ALUControl (LEDR[9:7]),
 .ALUSrcA (LEDR[6:5]),
 .ALUSrcB (LEDR[4:3]),
 .ImmSrcB (LEDR[2:1]),
 .RegWrite (LEDR[0])
);

endmodule
